spring:
  datasource:
      url: 'jdbc:mysql://10.10.1.100/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai'
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      username: 'root'
      password: 'Abc.123456'
  redis:
    host: 127.0.0.1
    port: 6379
  security:
    oauth2:
      storeType: redis
      jwt:
        SigningKey: oauth2